### ISSUE TITLE
Trouble exposing ports on docker

### ISSUE THREAD

**Issue by metalaureate** [lloydwatkin/prosody-docker#5]
@lloydwatkin @mwild1 This is a question not a bug... Hoping you can help me with the last pieces of deploying prosody. I'm deploying prosody to production using docker and I'm having some remedial trouble exposing BOSH. I cannot telnet or otherwise reach prosody on port 5280. I have the same problem on docker instances at EC2 as on my local docker instances. I'm certainly doing something stupid, just can't see it.

```
$ docker ps
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS              PORTS                                                               NAMES
32aaae1e91f1        idelog_xmpp:latest   "/bin/sh -c 'prosody   6 seconds ago       Up 9 seconds        80/tcp, 443/tcp, 5222/tcp, 5280/tcp, 5269/tcp, 5281/tcp, 5347/tcp   idelog_xmpp_run_1   
simon-hill-macbook-pro:idelog shill$ boot2docker ip
192.168.1.112
simon-hill-macbook-pro:idelog shill$ telnet 192.168.1.112 5280
Trying 192.168.1.112...
telnet: connect to address 192.168.1.112: Connection refused
```

My fig file looks like

```
redis:
    image: redis:latest
xmpp:
     build: ./xmpp/
     command: prosodyctl start
     ports:
         - "5280:5280" # xmpp bosh
         - "5222:5222" # xmpp native
web:
    build: ./web/
    command: npm start
    links:
        - xmpp
        - redis
    ports:
        - "80:80" # web
worker:
    build: ./worker/
    links:
        - redis
    command: npm start
cron:
     build: ./cron/
     links:
         - redis
     command: npm start
```
