### ISSUE TITLE
Problems connecting BOSH, attaching shell, and generating logs

### ISSUE THREAD

**Issue by metalaureate** [lloydwatkin/prosody-docker#7]
@mwild1 @lloydwatkin I'm running prosody in boot2docker locally at 192.168.1.109 and running into a problem with connecting by BOSH.

Despite having BOSH enabled in my config file

shill$ telnet 192.168.1.109 5222
Trying 192.168.1.109...
Connected to boot2docker.hsd1.ca.comcast.net.
Escape character is '^]'.
^]
telnet> Connection closed.
simon-hill-macbook-pro:idelog shill$ telnet 192.168.1.109 5280
Trying 192.168.1.109...
telnet: connect to address 192.168.1.109: Connection refused

Here's my fig config 

```
xmpp:
     build: ./xmpp/
     command: prosodyctl start
     volumes:
         - ./xmpp/configuration:/etc/prosody
         - ./xmpp/logs:/var/log/prosody
         - ./xmpp/modules:/usr/lib/prosody-modules
     ports:
         - "5280:5280" # xmpp bosh
         - "5222:5222" # xmpp native
```

prosody config in /etc/prosody
http://pastebin.com/Yq6au87y

Dockerfile
```
# xmpp
FROM prosody/prosody:latest
MAINTAINER simon@idelog.me
ENV LOCAL xxx
ENV PASSWORD xxx
ENV DOMAIN localhost
VOLUME /var/log/prosody/
VOLUME /etc/prosody
CMD prosodyctl start
```

fig run xmpp /bin/bash does not attach a shell, which makes debugging hard.

I get no logs in ./xmpp/logs

Any ideas how to troubleshoot this? Thank you. Prosody is the messaging backend for a consumer startup I am about to launch.

(Needless to say, prosody works fine on my local mac... my difficulties began when I dockerized prosody using your image.)
